spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/eshopblvd_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.8.41:8848
    gateway:
      routes:
        - id: product-route
          uri: lb://eshopblvd-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: thirdparty-route
          uri: lb://eshopblvd-thirdparty
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://eshopblvd-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://eshopblvd-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: search_route
          uri: lb://eshopblvd-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: auth_route
          uri: lb://eshopblvd-sso-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: cart_route
          uri: lb://eshopblvd-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://eshopblvd-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

#        - id: eshopblvd_host_route
#          uri: lb://eshopblvd-product
#          predicates:
#            - Host=eshopblvd.com,item.eshopblvd.com
#
#        - id: eshopblvd_search_route
#          uri: lb://eshopblvd-search
#          predicates:
#            - Host=search.eshopblvd.com
#
        - id: eshopblvd_ssoauth_route
          uri: lb://eshopblvd-sso-auth
          predicates:
            - Host=ssoauth.eshopblvd.com


  application:
    name: eshopblvd-gateway

server:
  port: 88