spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.103.8.41:3306/eshopblvd_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.8.41:8848
  application:
    name: eshopblvd-coupon

mybatis:
  mapper-locations: classpath*:com/hatsukoi/eshopblvd/coupon/mapper/*.xml

server:
  port: 7000