spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.8.41:8848
  application:
    name: eshopblvd-cart
  redis:
    host: 47.103.8.41
    port: 6379

server:
  port: 30000

dubbo:
  application:
    name: eshopblvd-cart-dubbo
  registry:
    address: nacos://47.103.8.41:8848
  monitor:
    protocol: registry
  protocol:
    port: 20900
  consumer:
    timeout: 60000
    retries: 3

eshopblvd:
  thread-pool:
    core-size: 20
    max-size: 200
    keep-alive-time: 10