spring:
  cloud:
    nacos:
      discovery:
        server-addr: xxx:8848
  application:
    name: eshopblvd-cart
  redis:
    host: xxx
    port: 6379
  session:
    store-type: redis

server:
  port: 30000

dubbo:
  application:
    name: eshopblvd-cart-dubbo
  registry:
    address: nacos://xxx:8848
  monitor:
    protocol: registry
  protocol:
    port: 20900
  consumer:
    timeout: 60000
    retries: 3

eshopblvd:
  thread-pool:
    core-size: 20
    max-size: 200
    keep-alive-time: 10