package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.CouponSpuCategoryRelation;
import com.hatsukoi.eshopblvd.coupon.entity.CouponSpuCategoryRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponSpuCategoryRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    long countByExample(CouponSpuCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int deleteByExample(CouponSpuCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int insert(CouponSpuCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int insertSelective(CouponSpuCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    List<CouponSpuCategoryRelation> selectByExample(CouponSpuCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    CouponSpuCategoryRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CouponSpuCategoryRelation record, @Param("example") CouponSpuCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CouponSpuCategoryRelation record, @Param("example") CouponSpuCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponSpuCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponSpuCategoryRelation record);
}