package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.CouponSpuRelation;
import com.hatsukoi.eshopblvd.coupon.entity.CouponSpuRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponSpuRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    long countByExample(CouponSpuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    int deleteByExample(CouponSpuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    int insert(CouponSpuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    int insertSelective(CouponSpuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    List<CouponSpuRelation> selectByExample(CouponSpuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    CouponSpuRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CouponSpuRelation record, @Param("example") CouponSpuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CouponSpuRelation record, @Param("example") CouponSpuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponSpuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponSpuRelation record);
}