package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.HomeSubject;
import com.hatsukoi.eshopblvd.coupon.entity.HomeSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    long countByExample(HomeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int deleteByExample(HomeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int insert(HomeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int insertSelective(HomeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    List<HomeSubject> selectByExample(HomeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    HomeSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HomeSubject record, @Param("example") HomeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HomeSubject record, @Param("example") HomeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HomeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HomeSubject record);
}