package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.HomeSubjectSpu;
import com.hatsukoi.eshopblvd.coupon.entity.HomeSubjectSpuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeSubjectSpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    long countByExample(HomeSubjectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    int deleteByExample(HomeSubjectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    int insert(HomeSubjectSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    int insertSelective(HomeSubjectSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    List<HomeSubjectSpu> selectByExample(HomeSubjectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    HomeSubjectSpu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HomeSubjectSpu record, @Param("example") HomeSubjectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HomeSubjectSpu record, @Param("example") HomeSubjectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HomeSubjectSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HomeSubjectSpu record);
}