package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.MemberPrice;
import com.hatsukoi.eshopblvd.coupon.entity.MemberPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    long countByExample(MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int deleteByExample(MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int insert(MemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int insertSelective(MemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    List<MemberPrice> selectByExample(MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    MemberPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberPrice record, @Param("example") MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberPrice record, @Param("example") MemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberPrice record);
}