package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.SeckillSkuNotice;
import com.hatsukoi.eshopblvd.coupon.entity.SeckillSkuNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillSkuNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    long countByExample(SeckillSkuNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int deleteByExample(SeckillSkuNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int insert(SeckillSkuNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int insertSelective(SeckillSkuNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    List<SeckillSkuNotice> selectByExample(SeckillSkuNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    SeckillSkuNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SeckillSkuNotice record, @Param("example") SeckillSkuNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SeckillSkuNotice record, @Param("example") SeckillSkuNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SeckillSkuNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SeckillSkuNotice record);
}