package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.SeckillSkuRelation;
import com.hatsukoi.eshopblvd.coupon.entity.SeckillSkuRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillSkuRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    long countByExample(SeckillSkuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int deleteByExample(SeckillSkuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int insert(SeckillSkuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int insertSelective(SeckillSkuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    List<SeckillSkuRelation> selectByExample(SeckillSkuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    SeckillSkuRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SeckillSkuRelation record, @Param("example") SeckillSkuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SeckillSkuRelation record, @Param("example") SeckillSkuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SeckillSkuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SeckillSkuRelation record);
}