package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.SeckillSession;
import com.hatsukoi.eshopblvd.coupon.entity.SeckillSessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    long countByExample(SeckillSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    int deleteByExample(SeckillSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    int insert(SeckillSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    int insertSelective(SeckillSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    List<SeckillSession> selectByExample(SeckillSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    SeckillSession selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SeckillSession record, @Param("example") SeckillSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SeckillSession record, @Param("example") SeckillSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SeckillSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SeckillSession record);
}