package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.SkuLadder;
import com.hatsukoi.eshopblvd.coupon.entity.SkuLadderExample;
import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

public interface SkuLadderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    long countByExample(SkuLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int deleteByExample(SkuLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(SkuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int insertSelective(SkuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    List<SkuLadder> selectByExample(SkuLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    SkuLadder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SkuLadder record, @Param("example") SkuLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SkuLadder record, @Param("example") SkuLadderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SkuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SkuLadder record);
}