package com.hatsukoi.eshopblvd.coupon.dao;

import com.hatsukoi.eshopblvd.coupon.entity.SpuBounds;
import com.hatsukoi.eshopblvd.coupon.entity.SpuBoundsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpuBoundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    long countByExample(SpuBoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    int deleteByExample(SpuBoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    int insert(SpuBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    int insertSelective(SpuBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    List<SpuBounds> selectByExample(SpuBoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    SpuBounds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpuBounds record, @Param("example") SpuBoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpuBounds record, @Param("example") SpuBoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpuBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpuBounds record);
}