package com.hatsukoi.eshopblvd.product.dao;

import com.hatsukoi.eshopblvd.product.entity.AttrGroup;
import com.hatsukoi.eshopblvd.product.entity.AttrGroupExample;
import java.util.List;

import com.hatsukoi.eshopblvd.product.entity.SpuItemAttrGroupPO;
import com.hatsukoi.eshopblvd.product.vo.SkuItemVO;
import org.apache.ibatis.annotations.Param;

public interface AttrGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    long countByExample(AttrGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int deleteByExample(AttrGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long attrGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int insert(AttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int insertSelective(AttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    List<AttrGroup> selectByExample(AttrGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    AttrGroup selectByPrimaryKey(Long attrGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AttrGroup record, @Param("example") AttrGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AttrGroup record, @Param("example") AttrGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AttrGroup record);

    List<SpuItemAttrGroupPO> getAttrGroupWithAttrsBySpuId(@Param("spuId") Long spuId, @Param("catalogId") Long catalogId);
}