package com.hatsukoi.eshopblvd.product.dao;

import com.hatsukoi.eshopblvd.product.entity.ProductAttrValue;
import com.hatsukoi.eshopblvd.product.entity.ProductAttrValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    long countByExample(ProductAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int deleteByExample(ProductAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int insert(ProductAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int insertSelective(ProductAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    List<ProductAttrValue> selectByExample(ProductAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    ProductAttrValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductAttrValue record, @Param("example") ProductAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductAttrValue record, @Param("example") ProductAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductAttrValue record);

    void batchInsert(@Param("attrValues") List<ProductAttrValue> collect);
}