package com.hatsukoi.eshopblvd.product.dao;

import com.hatsukoi.eshopblvd.product.entity.SpuComment;
import com.hatsukoi.eshopblvd.product.entity.SpuCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpuCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    long countByExample(SpuCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int deleteByExample(SpuCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int insert(SpuComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int insertSelective(SpuComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    List<SpuComment> selectByExampleWithBLOBs(SpuCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    List<SpuComment> selectByExample(SpuCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    SpuComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpuComment record, @Param("example") SpuCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") SpuComment record, @Param("example") SpuCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpuComment record, @Param("example") SpuCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpuComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SpuComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpuComment record);
}