package com.hatsukoi.eshopblvd.coupon.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_coupon_spu_category_relation
 */
public class CouponSpuCategoryRelation implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_category_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   优惠券id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_category_relation.coupon_id
     *
     * @mbg.generated
     */
    private Long couponId;

    /**
     * Database Column Remarks:
     *   产品分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_category_relation.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   产品分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_category_relation.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_category_relation.id
     *
     * @return the value of sms_coupon_spu_category_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_category_relation.id
     *
     * @param id the value for sms_coupon_spu_category_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_category_relation.coupon_id
     *
     * @return the value of sms_coupon_spu_category_relation.coupon_id
     *
     * @mbg.generated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_category_relation.coupon_id
     *
     * @param couponId the value for sms_coupon_spu_category_relation.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_category_relation.category_id
     *
     * @return the value of sms_coupon_spu_category_relation.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_category_relation.category_id
     *
     * @param categoryId the value for sms_coupon_spu_category_relation.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_category_relation.category_name
     *
     * @return the value of sms_coupon_spu_category_relation.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_category_relation.category_name
     *
     * @param categoryName the value for sms_coupon_spu_category_relation.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", couponId=").append(couponId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}