package com.hatsukoi.eshopblvd.coupon.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_home_subject
 */
public class HomeSubject implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   专题名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   专题标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   专题副标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject.sub_title
     *
     * @mbg.generated
     */
    private String subTitle;

    /**
     * Database Column Remarks:
     *   显示状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   详情连接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   专题图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject.id
     *
     * @return the value of sms_home_subject.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject.id
     *
     * @param id the value for sms_home_subject.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject.name
     *
     * @return the value of sms_home_subject.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject.name
     *
     * @param name the value for sms_home_subject.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject.title
     *
     * @return the value of sms_home_subject.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject.title
     *
     * @param title the value for sms_home_subject.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject.sub_title
     *
     * @return the value of sms_home_subject.sub_title
     *
     * @mbg.generated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject.sub_title
     *
     * @param subTitle the value for sms_home_subject.sub_title
     *
     * @mbg.generated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject.status
     *
     * @return the value of sms_home_subject.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject.status
     *
     * @param status the value for sms_home_subject.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject.url
     *
     * @return the value of sms_home_subject.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject.url
     *
     * @param url the value for sms_home_subject.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject.sort
     *
     * @return the value of sms_home_subject.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject.sort
     *
     * @param sort the value for sms_home_subject.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject.img
     *
     * @return the value of sms_home_subject.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject.img
     *
     * @param img the value for sms_home_subject.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", status=").append(status);
        sb.append(", url=").append(url);
        sb.append(", sort=").append(sort);
        sb.append(", img=").append(img);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}