package com.hatsukoi.eshopblvd.coupon.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_home_subject_spu
 */
public class HomeSubjectSpu implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject_spu.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   专题名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject_spu.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   专题id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject_spu.subject_id
     *
     * @mbg.generated
     */
    private Long subjectId;

    /**
     * Database Column Remarks:
     *   spu_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject_spu.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_subject_spu.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject_spu.id
     *
     * @return the value of sms_home_subject_spu.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject_spu.id
     *
     * @param id the value for sms_home_subject_spu.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject_spu.name
     *
     * @return the value of sms_home_subject_spu.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject_spu.name
     *
     * @param name the value for sms_home_subject_spu.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject_spu.subject_id
     *
     * @return the value of sms_home_subject_spu.subject_id
     *
     * @mbg.generated
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject_spu.subject_id
     *
     * @param subjectId the value for sms_home_subject_spu.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject_spu.spu_id
     *
     * @return the value of sms_home_subject_spu.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject_spu.spu_id
     *
     * @param spuId the value for sms_home_subject_spu.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_subject_spu.sort
     *
     * @return the value of sms_home_subject_spu.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_subject_spu.sort
     *
     * @param sort the value for sms_home_subject_spu.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject_spu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", spuId=").append(spuId);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}