package com.hatsukoi.eshopblvd.coupon.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_seckill_sku_notice
 */
public class SeckillSkuNotice implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_notice.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   member_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_notice.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     * Database Column Remarks:
     *   sku_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_notice.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   活动场次id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_notice.session_id
     *
     * @mbg.generated
     */
    private Long sessionId;

    /**
     * Database Column Remarks:
     *   订阅时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_notice.subcribe_time
     *
     * @mbg.generated
     */
    private Date subcribeTime;

    /**
     * Database Column Remarks:
     *   发送时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_notice.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     * Database Column Remarks:
     *   通知方式[0-短信，1-邮件]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_notice.notice_type
     *
     * @mbg.generated
     */
    private Boolean noticeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_notice.id
     *
     * @return the value of sms_seckill_sku_notice.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_notice.id
     *
     * @param id the value for sms_seckill_sku_notice.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_notice.member_id
     *
     * @return the value of sms_seckill_sku_notice.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_notice.member_id
     *
     * @param memberId the value for sms_seckill_sku_notice.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_notice.sku_id
     *
     * @return the value of sms_seckill_sku_notice.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_notice.sku_id
     *
     * @param skuId the value for sms_seckill_sku_notice.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_notice.session_id
     *
     * @return the value of sms_seckill_sku_notice.session_id
     *
     * @mbg.generated
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_notice.session_id
     *
     * @param sessionId the value for sms_seckill_sku_notice.session_id
     *
     * @mbg.generated
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_notice.subcribe_time
     *
     * @return the value of sms_seckill_sku_notice.subcribe_time
     *
     * @mbg.generated
     */
    public Date getSubcribeTime() {
        return subcribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_notice.subcribe_time
     *
     * @param subcribeTime the value for sms_seckill_sku_notice.subcribe_time
     *
     * @mbg.generated
     */
    public void setSubcribeTime(Date subcribeTime) {
        this.subcribeTime = subcribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_notice.send_time
     *
     * @return the value of sms_seckill_sku_notice.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_notice.send_time
     *
     * @param sendTime the value for sms_seckill_sku_notice.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_notice.notice_type
     *
     * @return the value of sms_seckill_sku_notice.notice_type
     *
     * @mbg.generated
     */
    public Boolean getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_notice.notice_type
     *
     * @param noticeType the value for sms_seckill_sku_notice.notice_type
     *
     * @mbg.generated
     */
    public void setNoticeType(Boolean noticeType) {
        this.noticeType = noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", skuId=").append(skuId);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", subcribeTime=").append(subcribeTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", noticeType=").append(noticeType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}