package com.hatsukoi.eshopblvd.coupon.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_seckill_sku_relation
 */
public class SeckillSkuRelation implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   活动id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_relation.promotion_id
     *
     * @mbg.generated
     */
    private Long promotionId;

    /**
     * Database Column Remarks:
     *   活动场次id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_relation.promotion_session_id
     *
     * @mbg.generated
     */
    private Long promotionSessionId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_relation.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   秒杀价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_relation.seckill_price
     *
     * @mbg.generated
     */
    private Long seckillPrice;

    /**
     * Database Column Remarks:
     *   秒杀总量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_relation.seckill_count
     *
     * @mbg.generated
     */
    private Long seckillCount;

    /**
     * Database Column Remarks:
     *   每人限购数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_relation.seckill_limit
     *
     * @mbg.generated
     */
    private Long seckillLimit;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_sku_relation.seckill_sort
     *
     * @mbg.generated
     */
    private Integer seckillSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_relation.id
     *
     * @return the value of sms_seckill_sku_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_relation.id
     *
     * @param id the value for sms_seckill_sku_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_relation.promotion_id
     *
     * @return the value of sms_seckill_sku_relation.promotion_id
     *
     * @mbg.generated
     */
    public Long getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_relation.promotion_id
     *
     * @param promotionId the value for sms_seckill_sku_relation.promotion_id
     *
     * @mbg.generated
     */
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_relation.promotion_session_id
     *
     * @return the value of sms_seckill_sku_relation.promotion_session_id
     *
     * @mbg.generated
     */
    public Long getPromotionSessionId() {
        return promotionSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_relation.promotion_session_id
     *
     * @param promotionSessionId the value for sms_seckill_sku_relation.promotion_session_id
     *
     * @mbg.generated
     */
    public void setPromotionSessionId(Long promotionSessionId) {
        this.promotionSessionId = promotionSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_relation.sku_id
     *
     * @return the value of sms_seckill_sku_relation.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_relation.sku_id
     *
     * @param skuId the value for sms_seckill_sku_relation.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_relation.seckill_price
     *
     * @return the value of sms_seckill_sku_relation.seckill_price
     *
     * @mbg.generated
     */
    public Long getSeckillPrice() {
        return seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_relation.seckill_price
     *
     * @param seckillPrice the value for sms_seckill_sku_relation.seckill_price
     *
     * @mbg.generated
     */
    public void setSeckillPrice(Long seckillPrice) {
        this.seckillPrice = seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_relation.seckill_count
     *
     * @return the value of sms_seckill_sku_relation.seckill_count
     *
     * @mbg.generated
     */
    public Long getSeckillCount() {
        return seckillCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_relation.seckill_count
     *
     * @param seckillCount the value for sms_seckill_sku_relation.seckill_count
     *
     * @mbg.generated
     */
    public void setSeckillCount(Long seckillCount) {
        this.seckillCount = seckillCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_relation.seckill_limit
     *
     * @return the value of sms_seckill_sku_relation.seckill_limit
     *
     * @mbg.generated
     */
    public Long getSeckillLimit() {
        return seckillLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_relation.seckill_limit
     *
     * @param seckillLimit the value for sms_seckill_sku_relation.seckill_limit
     *
     * @mbg.generated
     */
    public void setSeckillLimit(Long seckillLimit) {
        this.seckillLimit = seckillLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_seckill_sku_relation.seckill_sort
     *
     * @return the value of sms_seckill_sku_relation.seckill_sort
     *
     * @mbg.generated
     */
    public Integer getSeckillSort() {
        return seckillSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_seckill_sku_relation.seckill_sort
     *
     * @param seckillSort the value for sms_seckill_sku_relation.seckill_sort
     *
     * @mbg.generated
     */
    public void setSeckillSort(Integer seckillSort) {
        this.seckillSort = seckillSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", promotionId=").append(promotionId);
        sb.append(", promotionSessionId=").append(promotionSessionId);
        sb.append(", skuId=").append(skuId);
        sb.append(", seckillPrice=").append(seckillPrice);
        sb.append(", seckillCount=").append(seckillCount);
        sb.append(", seckillLimit=").append(seckillLimit);
        sb.append(", seckillSort=").append(seckillSort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}