package com.hatsukoi.eshopblvd.coupon.entity;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_sku_full_reduction
 */
public class SkuFullReduction implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_full_reduction.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   spu_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_full_reduction.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   满多少
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_full_reduction.full_price
     *
     * @mbg.generated
     */
    private BigDecimal fullPrice;

    /**
     * Database Column Remarks:
     *   减多少
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_full_reduction.reduce_price
     *
     * @mbg.generated
     */
    private BigDecimal reducePrice;

    /**
     * Database Column Remarks:
     *   是否参与其他优惠
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_full_reduction.add_other
     *
     * @mbg.generated
     */
    private Boolean addOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_sku_full_reduction
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_full_reduction.id
     *
     * @return the value of sms_sku_full_reduction.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_full_reduction.id
     *
     * @param id the value for sms_sku_full_reduction.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_full_reduction.sku_id
     *
     * @return the value of sms_sku_full_reduction.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_full_reduction.sku_id
     *
     * @param skuId the value for sms_sku_full_reduction.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_full_reduction.full_price
     *
     * @return the value of sms_sku_full_reduction.full_price
     *
     * @mbg.generated
     */
    public BigDecimal getFullPrice() {
        return fullPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_full_reduction.full_price
     *
     * @param fullPrice the value for sms_sku_full_reduction.full_price
     *
     * @mbg.generated
     */
    public void setFullPrice(BigDecimal fullPrice) {
        this.fullPrice = fullPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_full_reduction.reduce_price
     *
     * @return the value of sms_sku_full_reduction.reduce_price
     *
     * @mbg.generated
     */
    public BigDecimal getReducePrice() {
        return reducePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_full_reduction.reduce_price
     *
     * @param reducePrice the value for sms_sku_full_reduction.reduce_price
     *
     * @mbg.generated
     */
    public void setReducePrice(BigDecimal reducePrice) {
        this.reducePrice = reducePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_full_reduction.add_other
     *
     * @return the value of sms_sku_full_reduction.add_other
     *
     * @mbg.generated
     */
    public Boolean getAddOther() {
        return addOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_full_reduction.add_other
     *
     * @param addOther the value for sms_sku_full_reduction.add_other
     *
     * @mbg.generated
     */
    public void setAddOther(Boolean addOther) {
        this.addOther = addOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_full_reduction
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", skuId=").append(skuId);
        sb.append(", fullPrice=").append(fullPrice);
        sb.append(", reducePrice=").append(reducePrice);
        sb.append(", addOther=").append(addOther);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}