package com.hatsukoi.eshopblvd.coupon.entity;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_spu_bounds
 */
public class SpuBounds implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_bounds.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_bounds.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   成长积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_bounds.grow_bounds
     *
     * @mbg.generated
     */
    private BigDecimal growBounds;

    /**
     * Database Column Remarks:
     *   购物积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_bounds.buy_bounds
     *
     * @mbg.generated
     */
    private BigDecimal buyBounds;

    /**
     * Database Column Remarks:
     *   优惠生效情况[1111（四个状态位，从右到左）;0 - 无优惠，成长积分是否赠送;1 - 无优惠，购物积分是否赠送;2 - 有优惠，成长积分是否赠送;3 - 有优惠，购物积分是否赠送【状态位0：不赠送，1：赠送】]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_bounds.work
     *
     * @mbg.generated
     */
    private Boolean work;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_bounds.id
     *
     * @return the value of sms_spu_bounds.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_bounds.id
     *
     * @param id the value for sms_spu_bounds.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_bounds.spu_id
     *
     * @return the value of sms_spu_bounds.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_bounds.spu_id
     *
     * @param spuId the value for sms_spu_bounds.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_bounds.grow_bounds
     *
     * @return the value of sms_spu_bounds.grow_bounds
     *
     * @mbg.generated
     */
    public BigDecimal getGrowBounds() {
        return growBounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_bounds.grow_bounds
     *
     * @param growBounds the value for sms_spu_bounds.grow_bounds
     *
     * @mbg.generated
     */
    public void setGrowBounds(BigDecimal growBounds) {
        this.growBounds = growBounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_bounds.buy_bounds
     *
     * @return the value of sms_spu_bounds.buy_bounds
     *
     * @mbg.generated
     */
    public BigDecimal getBuyBounds() {
        return buyBounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_bounds.buy_bounds
     *
     * @param buyBounds the value for sms_spu_bounds.buy_bounds
     *
     * @mbg.generated
     */
    public void setBuyBounds(BigDecimal buyBounds) {
        this.buyBounds = buyBounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_bounds.work
     *
     * @return the value of sms_spu_bounds.work
     *
     * @mbg.generated
     */
    public Boolean getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_bounds.work
     *
     * @param work the value for sms_spu_bounds.work
     *
     * @mbg.generated
     */
    public void setWork(Boolean work) {
        this.work = work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_bounds
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", spuId=").append(spuId);
        sb.append(", growBounds=").append(growBounds);
        sb.append(", buyBounds=").append(buyBounds);
        sb.append(", work=").append(work);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}