spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/eshopblvd_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.8.41:8848
  application:
    name: eshopblvd-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 47.103.8.41
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 360000
      use-key-prefix: true
      cache-null-values: true
      key-prefix: CACHE_

mybatis:
  mapper-locations: classpath*:com/hatsukoi/eshopblvd/product/mapper/*.xml

server:
  port: 10000

dubbo:
  application:
    name: eshopblvd-product-dubbo
  registry:
    address: nacos://47.103.8.41:8848
  monitor:
    protocol: registry
  protocol:
    port: 20880
  consumer:
    timeout: 60000
    retries: 3

eshopblvd:
  thread-pool:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
#logging:
#  level:
#    com.hatsukoi.eshopblvd: debug