package com.hatsukoi.eshopblvd.member.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_member_collect_spu
 */
public class MemberCollectSpu implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_collect_spu.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   会员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_collect_spu.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     * Database Column Remarks:
     *   spu_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_collect_spu.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   spu_name
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_collect_spu.spu_name
     *
     * @mbg.generated
     */
    private String spuName;

    /**
     * Database Column Remarks:
     *   spu_img
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_collect_spu.spu_img
     *
     * @mbg.generated
     */
    private String spuImg;

    /**
     * Database Column Remarks:
     *   create_time
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_collect_spu.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_collect_spu.id
     *
     * @return the value of ums_member_collect_spu.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_collect_spu.id
     *
     * @param id the value for ums_member_collect_spu.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_collect_spu.member_id
     *
     * @return the value of ums_member_collect_spu.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_collect_spu.member_id
     *
     * @param memberId the value for ums_member_collect_spu.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_collect_spu.spu_id
     *
     * @return the value of ums_member_collect_spu.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_collect_spu.spu_id
     *
     * @param spuId the value for ums_member_collect_spu.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_collect_spu.spu_name
     *
     * @return the value of ums_member_collect_spu.spu_name
     *
     * @mbg.generated
     */
    public String getSpuName() {
        return spuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_collect_spu.spu_name
     *
     * @param spuName the value for ums_member_collect_spu.spu_name
     *
     * @mbg.generated
     */
    public void setSpuName(String spuName) {
        this.spuName = spuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_collect_spu.spu_img
     *
     * @return the value of ums_member_collect_spu.spu_img
     *
     * @mbg.generated
     */
    public String getSpuImg() {
        return spuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_collect_spu.spu_img
     *
     * @param spuImg the value for ums_member_collect_spu.spu_img
     *
     * @mbg.generated
     */
    public void setSpuImg(String spuImg) {
        this.spuImg = spuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_collect_spu.create_time
     *
     * @return the value of ums_member_collect_spu.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_collect_spu.create_time
     *
     * @param createTime the value for ums_member_collect_spu.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", spuId=").append(spuId);
        sb.append(", spuName=").append(spuName);
        sb.append(", spuImg=").append(spuImg);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}