package com.hatsukoi.eshopblvd.member.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_member_receive_address
 */
public class MemberReceiveAddress implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   member_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     * Database Column Remarks:
     *   收货人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   邮政编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.post_code
     *
     * @mbg.generated
     */
    private String postCode;

    /**
     * Database Column Remarks:
     *   省份/直辖市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * Database Column Remarks:
     *   详细地址(街道)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.detail_address
     *
     * @mbg.generated
     */
    private String detailAddress;

    /**
     * Database Column Remarks:
     *   省市区代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.areacode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     * Database Column Remarks:
     *   是否默认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_receive_address.default_status
     *
     * @mbg.generated
     */
    private Boolean defaultStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.id
     *
     * @return the value of ums_member_receive_address.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.id
     *
     * @param id the value for ums_member_receive_address.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.member_id
     *
     * @return the value of ums_member_receive_address.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.member_id
     *
     * @param memberId the value for ums_member_receive_address.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.name
     *
     * @return the value of ums_member_receive_address.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.name
     *
     * @param name the value for ums_member_receive_address.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.phone
     *
     * @return the value of ums_member_receive_address.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.phone
     *
     * @param phone the value for ums_member_receive_address.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.post_code
     *
     * @return the value of ums_member_receive_address.post_code
     *
     * @mbg.generated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.post_code
     *
     * @param postCode the value for ums_member_receive_address.post_code
     *
     * @mbg.generated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.province
     *
     * @return the value of ums_member_receive_address.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.province
     *
     * @param province the value for ums_member_receive_address.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.city
     *
     * @return the value of ums_member_receive_address.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.city
     *
     * @param city the value for ums_member_receive_address.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.region
     *
     * @return the value of ums_member_receive_address.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.region
     *
     * @param region the value for ums_member_receive_address.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.detail_address
     *
     * @return the value of ums_member_receive_address.detail_address
     *
     * @mbg.generated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.detail_address
     *
     * @param detailAddress the value for ums_member_receive_address.detail_address
     *
     * @mbg.generated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.areacode
     *
     * @return the value of ums_member_receive_address.areacode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.areacode
     *
     * @param areacode the value for ums_member_receive_address.areacode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_receive_address.default_status
     *
     * @return the value of ums_member_receive_address.default_status
     *
     * @mbg.generated
     */
    public Boolean getDefaultStatus() {
        return defaultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_receive_address.default_status
     *
     * @param defaultStatus the value for ums_member_receive_address.default_status
     *
     * @mbg.generated
     */
    public void setDefaultStatus(Boolean defaultStatus) {
        this.defaultStatus = defaultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_receive_address
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", name=").append(name);
        sb.append(", phone=").append(phone);
        sb.append(", postCode=").append(postCode);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", region=").append(region);
        sb.append(", detailAddress=").append(detailAddress);
        sb.append(", areacode=").append(areacode);
        sb.append(", defaultStatus=").append(defaultStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}