package com.hatsukoi.eshopblvd.order.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table oms_payment_info
 */
public class PaymentInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单号（对外业务号）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     * Database Column Remarks:
     *   支付宝交易流水号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.alipay_trade_no
     *
     * @mbg.generated
     */
    private String alipayTradeNo;

    /**
     * Database Column Remarks:
     *   支付总金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.total_amount
     *
     * @mbg.generated
     */
    private BigDecimal totalAmount;

    /**
     * Database Column Remarks:
     *   交易内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     * Database Column Remarks:
     *   支付状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.payment_status
     *
     * @mbg.generated
     */
    private String paymentStatus;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   确认时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.confirm_time
     *
     * @mbg.generated
     */
    private Date confirmTime;

    /**
     * Database Column Remarks:
     *   回调内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.callback_content
     *
     * @mbg.generated
     */
    private String callbackContent;

    /**
     * Database Column Remarks:
     *   回调时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_payment_info.callback_time
     *
     * @mbg.generated
     */
    private Date callbackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_payment_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.id
     *
     * @return the value of oms_payment_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.id
     *
     * @param id the value for oms_payment_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.order_sn
     *
     * @return the value of oms_payment_info.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.order_sn
     *
     * @param orderSn the value for oms_payment_info.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.order_id
     *
     * @return the value of oms_payment_info.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.order_id
     *
     * @param orderId the value for oms_payment_info.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.alipay_trade_no
     *
     * @return the value of oms_payment_info.alipay_trade_no
     *
     * @mbg.generated
     */
    public String getAlipayTradeNo() {
        return alipayTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.alipay_trade_no
     *
     * @param alipayTradeNo the value for oms_payment_info.alipay_trade_no
     *
     * @mbg.generated
     */
    public void setAlipayTradeNo(String alipayTradeNo) {
        this.alipayTradeNo = alipayTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.total_amount
     *
     * @return the value of oms_payment_info.total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.total_amount
     *
     * @param totalAmount the value for oms_payment_info.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.subject
     *
     * @return the value of oms_payment_info.subject
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.subject
     *
     * @param subject the value for oms_payment_info.subject
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.payment_status
     *
     * @return the value of oms_payment_info.payment_status
     *
     * @mbg.generated
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.payment_status
     *
     * @param paymentStatus the value for oms_payment_info.payment_status
     *
     * @mbg.generated
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.create_time
     *
     * @return the value of oms_payment_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.create_time
     *
     * @param createTime the value for oms_payment_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.confirm_time
     *
     * @return the value of oms_payment_info.confirm_time
     *
     * @mbg.generated
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.confirm_time
     *
     * @param confirmTime the value for oms_payment_info.confirm_time
     *
     * @mbg.generated
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.callback_content
     *
     * @return the value of oms_payment_info.callback_content
     *
     * @mbg.generated
     */
    public String getCallbackContent() {
        return callbackContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.callback_content
     *
     * @param callbackContent the value for oms_payment_info.callback_content
     *
     * @mbg.generated
     */
    public void setCallbackContent(String callbackContent) {
        this.callbackContent = callbackContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_payment_info.callback_time
     *
     * @return the value of oms_payment_info.callback_time
     *
     * @mbg.generated
     */
    public Date getCallbackTime() {
        return callbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_payment_info.callback_time
     *
     * @param callbackTime the value for oms_payment_info.callback_time
     *
     * @mbg.generated
     */
    public void setCallbackTime(Date callbackTime) {
        this.callbackTime = callbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_payment_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", orderId=").append(orderId);
        sb.append(", alipayTradeNo=").append(alipayTradeNo);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", subject=").append(subject);
        sb.append(", paymentStatus=").append(paymentStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", confirmTime=").append(confirmTime);
        sb.append(", callbackContent=").append(callbackContent);
        sb.append(", callbackTime=").append(callbackTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}