spring:
  cloud:
    nacos:
      discovery:
        server-addr: xxx:8848
  application:
    name: eshopblvd-sso-auth
  redis:
    host: xxx
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    cache: false

server:
  port: 20000
  servlet:
    session:
      timeout: 300m

dubbo:
  application:
    name: eshopblvd-sso-auth-dubbo
  registry:
    address: nacos://xxx:8848
  monitor:
    protocol: registry
  protocol:
    port: 20886
  consumer:
    timeout: 60000
    retries: 3