package com.hatsukoi.eshopblvd.order.dao;

import com.hatsukoi.eshopblvd.order.entity.RefundInfo;
import com.hatsukoi.eshopblvd.order.entity.RefundInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    long countByExample(RefundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    int deleteByExample(RefundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    int insert(RefundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    int insertSelective(RefundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    List<RefundInfo> selectByExample(RefundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    RefundInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RefundInfo record, @Param("example") RefundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RefundInfo record, @Param("example") RefundInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RefundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_refund_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RefundInfo record);
}