package com.hatsukoi.eshopblvd.ware.dao;

import com.hatsukoi.eshopblvd.ware.entity.WareOrderTaskDetail;
import com.hatsukoi.eshopblvd.ware.entity.WareOrderTaskDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WareOrderTaskDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    long countByExample(WareOrderTaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    int deleteByExample(WareOrderTaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    int insert(WareOrderTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    int insertSelective(WareOrderTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    List<WareOrderTaskDetail> selectByExample(WareOrderTaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    WareOrderTaskDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WareOrderTaskDetail record, @Param("example") WareOrderTaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WareOrderTaskDetail record, @Param("example") WareOrderTaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WareOrderTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WareOrderTaskDetail record);
}