package com.hatsukoi.eshopblvd.ware.dao;

import com.hatsukoi.eshopblvd.ware.entity.WareOrderTask;
import com.hatsukoi.eshopblvd.ware.entity.WareOrderTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WareOrderTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    long countByExample(WareOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    int deleteByExample(WareOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    int insert(WareOrderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    int insertSelective(WareOrderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    List<WareOrderTask> selectByExample(WareOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    WareOrderTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WareOrderTask record, @Param("example") WareOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WareOrderTask record, @Param("example") WareOrderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WareOrderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_ware_order_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WareOrderTask record);
}