package com.hatsukoi.eshopblvd.member.dao;

import com.hatsukoi.eshopblvd.member.entity.MemberStatisticsInfo;
import com.hatsukoi.eshopblvd.member.entity.MemberStatisticsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberStatisticsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    long countByExample(MemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    int deleteByExample(MemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    int insert(MemberStatisticsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    int insertSelective(MemberStatisticsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    List<MemberStatisticsInfo> selectByExample(MemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    MemberStatisticsInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberStatisticsInfo record, @Param("example") MemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberStatisticsInfo record, @Param("example") MemberStatisticsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberStatisticsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_statistics_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberStatisticsInfo record);
}