package com.hatsukoi.eshopblvd.member.dao;

import com.hatsukoi.eshopblvd.member.entity.MemberCollectSpu;
import com.hatsukoi.eshopblvd.member.entity.MemberCollectSpuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberCollectSpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    long countByExample(MemberCollectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    int deleteByExample(MemberCollectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    int insert(MemberCollectSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    int insertSelective(MemberCollectSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    List<MemberCollectSpu> selectByExample(MemberCollectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    MemberCollectSpu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberCollectSpu record, @Param("example") MemberCollectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberCollectSpu record, @Param("example") MemberCollectSpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberCollectSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_collect_spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberCollectSpu record);
}