package com.hatsukoi.eshopblvd.product.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_category_brand_relation
 */
public class CategoryBrandRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_category_brand_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   品牌id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_category_brand_relation.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     * Database Column Remarks:
     *   分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_category_brand_relation.catelog_id
     *
     * @mbg.generated
     */
    private Long catelogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_category_brand_relation.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_category_brand_relation.catelog_name
     *
     * @mbg.generated
     */
    private String catelogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_category_brand_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_category_brand_relation.id
     *
     * @return the value of pms_category_brand_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_category_brand_relation.id
     *
     * @param id the value for pms_category_brand_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_category_brand_relation.brand_id
     *
     * @return the value of pms_category_brand_relation.brand_id
     *
     * @mbg.generated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_category_brand_relation.brand_id
     *
     * @param brandId the value for pms_category_brand_relation.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_category_brand_relation.catelog_id
     *
     * @return the value of pms_category_brand_relation.catelog_id
     *
     * @mbg.generated
     */
    public Long getCatelogId() {
        return catelogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_category_brand_relation.catelog_id
     *
     * @param catelogId the value for pms_category_brand_relation.catelog_id
     *
     * @mbg.generated
     */
    public void setCatelogId(Long catelogId) {
        this.catelogId = catelogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_category_brand_relation.brand_name
     *
     * @return the value of pms_category_brand_relation.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_category_brand_relation.brand_name
     *
     * @param brandName the value for pms_category_brand_relation.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_category_brand_relation.catelog_name
     *
     * @return the value of pms_category_brand_relation.catelog_name
     *
     * @mbg.generated
     */
    public String getCatelogName() {
        return catelogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_category_brand_relation.catelog_name
     *
     * @param catelogName the value for pms_category_brand_relation.catelog_name
     *
     * @mbg.generated
     */
    public void setCatelogName(String catelogName) {
        this.catelogName = catelogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_category_brand_relation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brandId=").append(brandId);
        sb.append(", catelogId=").append(catelogId);
        sb.append(", brandName=").append(brandName);
        sb.append(", catelogName=").append(catelogName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}