package com.hatsukoi.eshopblvd.product.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_product_attr_value
 */
public class ProductAttrValue implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attr_value.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attr_value.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   属性id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attr_value.attr_id
     *
     * @mbg.generated
     */
    private Long attrId;

    /**
     * Database Column Remarks:
     *   属性名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attr_value.attr_name
     *
     * @mbg.generated
     */
    private String attrName;

    /**
     * Database Column Remarks:
     *   属性值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attr_value.attr_value
     *
     * @mbg.generated
     */
    private String attrValue;

    /**
     * Database Column Remarks:
     *   顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attr_value.attr_sort
     *
     * @mbg.generated
     */
    private Integer attrSort;

    /**
     * Database Column Remarks:
     *   快速展示【是否展示在介绍上；0-否 1-是】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attr_value.quick_show
     *
     * @mbg.generated
     */
    private Byte quickShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attr_value.id
     *
     * @return the value of pms_product_attr_value.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attr_value.id
     *
     * @param id the value for pms_product_attr_value.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attr_value.spu_id
     *
     * @return the value of pms_product_attr_value.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attr_value.spu_id
     *
     * @param spuId the value for pms_product_attr_value.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attr_value.attr_id
     *
     * @return the value of pms_product_attr_value.attr_id
     *
     * @mbg.generated
     */
    public Long getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attr_value.attr_id
     *
     * @param attrId the value for pms_product_attr_value.attr_id
     *
     * @mbg.generated
     */
    public void setAttrId(Long attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attr_value.attr_name
     *
     * @return the value of pms_product_attr_value.attr_name
     *
     * @mbg.generated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attr_value.attr_name
     *
     * @param attrName the value for pms_product_attr_value.attr_name
     *
     * @mbg.generated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attr_value.attr_value
     *
     * @return the value of pms_product_attr_value.attr_value
     *
     * @mbg.generated
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attr_value.attr_value
     *
     * @param attrValue the value for pms_product_attr_value.attr_value
     *
     * @mbg.generated
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attr_value.attr_sort
     *
     * @return the value of pms_product_attr_value.attr_sort
     *
     * @mbg.generated
     */
    public Integer getAttrSort() {
        return attrSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attr_value.attr_sort
     *
     * @param attrSort the value for pms_product_attr_value.attr_sort
     *
     * @mbg.generated
     */
    public void setAttrSort(Integer attrSort) {
        this.attrSort = attrSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attr_value.quick_show
     *
     * @return the value of pms_product_attr_value.quick_show
     *
     * @mbg.generated
     */
    public Byte getQuickShow() {
        return quickShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attr_value.quick_show
     *
     * @param quickShow the value for pms_product_attr_value.quick_show
     *
     * @mbg.generated
     */
    public void setQuickShow(Byte quickShow) {
        this.quickShow = quickShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", spuId=").append(spuId);
        sb.append(", attrId=").append(attrId);
        sb.append(", attrName=").append(attrName);
        sb.append(", attrValue=").append(attrValue);
        sb.append(", attrSort=").append(attrSort);
        sb.append(", quickShow=").append(quickShow);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}